"""Add/update tables

Revision ID: 91058e9f5bd7
Revises: 8e4858058c5b
Create Date: 2025-04-03 00:33:37.638011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91058e9f5bd7'
down_revision = '8e4858058c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
